name: rc_kolesa
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.3.1
  flutter_svg: ^1.1.6
  get: ^4.3.8
  cupertino_icons: ^1.0.2
  firebase_core: ^2.2.0
  gsheets: ^0.4.2
  html: ^0.15.1
  http: ^0.13.4
  firebase_storage: ^11.0.5
  firebase_database: ^10.0.5
  firebase_crashlytics: ^3.0.5
  firebase_messaging: ^14.1.0
  firebase_auth: ^4.1.2
  firebase_analytics: ^10.0.5
  cloud_firestore: ^4.4.5
  shimmer: ^2.0.0
  flutter_linkify: ^5.0.2
  webview_flutter: ^4.0.1
  url_launcher: ^6.1.5
  flutter_native_splash: ^2.2.0+1
  animated_splash_screen: ^1.3.0
  splashscreen: ^1.3.5
  shared_preferences: ^2.0.16
  flutter_spinkit: ^5.1.0
  flutter_cache_manager: ^3.3.0
  bottom_bar_page_transition: ^2.0.0
  curved_navigation_bar: ^1.0.3
  google_sign_in: ^5.4.1
  animated_background: ^2.0.0
  animated_text_kit: ^4.2.2
  google_fonts: ^3.0.1
  flutter_signin_button: ^2.0.0
  animate_icons: ^2.0.0
  fading_edge_scrollview: ^3.0.0
  shaky_animated_listview: ^0.0.5
  flutter_staggered_animations: ^1.0.0
  intl: ^0.18.0
  infinite_scroll_pagination: ^3.2.0
  cached_network_image: ^3.2.1
  flutter_countdown_timer: ^4.1.0
  envied: ^0.3.0
  firebase_core_platform_interface: ^4.5.2
  meta: ^1.7.0
  auto_size_text: ^3.0.0
  upgrader: ^5.1.0
  page_transition: ^2.0.9
  animated_theme_switcher: ^2.0.8
  toggle_switch: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences: "2.0.16"

  flutter_lints: ^2.0.0
  envied_generator: ^0.3.0
  build_runner: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/pics/