// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg3y57Ig32Q1wFsuksscTYzowAJT5-p18',
    appId: '1:127491625837:web:c6c80c1bcd8ef85e3ec064',
    messagingSenderId: '127491625837',
    projectId: 'kolesa-c00a2',
    authDomain: 'kolesa-c00a2.firebaseapp.com',
    storageBucket: 'kolesa-c00a2.appspot.com',
    measurementId: 'G-0W5VPMGBV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM7busGyB8mS1bITEDDZ2miyNKmimKSEU',
    appId: '1:127491625837:android:fdbec35f31f29a293ec064',
    messagingSenderId: '127491625837',
    projectId: 'kolesa-c00a2',
    storageBucket: 'kolesa-c00a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDirEZwViJkaHxTg3iC8O4Z3AmkXCtwTso',
    appId: '1:127491625837:ios:0821c528687e66dc3ec064',
    messagingSenderId: '127491625837',
    projectId: 'kolesa-c00a2',
    storageBucket: 'kolesa-c00a2.appspot.com',
    iosClientId: '127491625837-jga918rql6lt6u4nf6k9arenosa8gri1.apps.googleusercontent.com',
    iosBundleId: 'com.example.rcKolesa',
  );
}
